### ISSUE TITLE
Website not open

### ISSUE THREAD

**Issue by krryptonian** [DavidHDev/react-haiku#12]
![image](https://github.com/DavidHDev/react-haiku/assets/57591469/b14817b7-0313-4e2e-a0b6-51576a1cbacb)

**Comment by SeanWhelan** [comment]
I'm not sure what's going on with the official React Haiku docs domain, but in the meantime they can be accessed [here](https://haiku-docs-davidhdev.vercel.app).

**Comment by DavidHDev** [comment]
I no longer have access to the original domain, so I had to change the homepage to be accessible directly on [Vercel](https://haiku-docs-davidhdev.vercel.app/). If there are any instances in this repo where I forgot to change the link, please feel free to open a PR with the changes. Have a good one!
