### ISSUE TITLE
[FEAT] Create useInterval() hook

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#15]
Description:
Develop a custom React Hook, useInterval(), which allows scheduling a callback function to be executed at a specified interval.

Acceptance Criteria:

- [ ] The useInterval() hook should take a callback function and an interval duration as parameters.
- [ ] The hook should start executing the callback function repeatedly at the specified interval.
- [ ] Provide a way to pause or stop the interval execution.

**Comment by aadityarajkumawat** [comment]
Can I take this issue?

**Comment by DavidHDev** [comment]
Sure thing, if you want to take something please assign yourself to it and work on it in your own time. If you want to know more about contributing please read the CONTRIBUTING.MD file in the root folder. Me or someone else will then review your pull request.
