### ISSUE TITLE
[FEAT] Create useFullscreen() hook

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#16]
Description:
Create a custom React Hook, useFullscreen(), that enables toggling the fullscreen mode of an element.

Acceptance Criteria:

- [ ] The useFullscreen() hook should provide functions or state variables to manage the fullscreen mode.
- [ ] It should allow entering and exiting fullscreen mode.

**Comment by Vinny-Bass** [comment]
Can I get this one ?
