### ISSUE TITLE
[FEAT] Create useSize() hook

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#17]
Description:
Implement a custom React Hook, useSize(), that provides information about the dimensions of an element.

Acceptance Criteria:

- [ ] The useSize() hook should return the width and height of the target element.
- [ ] Ensure the hook updates the dimensions as the element size changes.

**Comment by ashishsurya** [comment]
Hey I can work on this issue, assign this to me @DavidHDev

**Comment by DavidHDev** [comment]
All yours!

**Comment by ashishsurya** [comment]
Hey completed working on this, opened a pull request #36

**Comment by ashishsurya** [comment]
committed the requested changes and updates @DavidHDev

**Comment by DavidHDev** [comment]
please fix the conflict and it can be merged @ashishsurya

**Comment by DavidHDev** [comment]
Implemented by @ashishsurya
