### ISSUE TITLE
[FEAT] Create useBatteryStatus() hook

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#18]
Description:
Develop a custom React Hook, useBatteryStatus(), that allows retrieving the current battery status of the user's device.

Acceptance Criteria:

- [ ] The useBatteryStatus() hook should provide information about the battery level and charging status.
- [ ] Ensure the hook updates the battery status in real-time as it changes.

**Comment by Vinny-Bass** [comment]
Hello, can I get this one? :)
