### ISSUE TITLE
[FEAT] Create useDeviceOS() hook

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#19]
Description:
Create a custom React Hook, useDeviceOS(), that detects and provides information about the user's operating system.

Acceptance Criteria:

- [ ] The useDeviceOS() hook should identify the user's operating system (e.g., Windows, macOS, iOS, Android).

**Comment by hmza98** [comment]
Hi David, can I take this issue?

**Comment by DavidHDev** [comment]
Sure, I'll assign it to you!
