### ISSUE TITLE
[FEAT] Create useTabNotification() hook

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#20]
Description:
Develop a custom React Hook, useTabNotification(), that enables displaying notifications on the browser tab.

Acceptance Criteria:

- [ ] The useTabNotification() hook should provide functions or state variables to manage the tab notification state.
- [ ] It should allow showing and hiding notifications on the tab.

**Comment by grafogeum** [comment]
I'd like to try this one

**Comment by Yeine** [comment]
@grafogeum I've already submitted a PR for it

**Comment by grafogeum** [comment]
ok thanks for letting me know, I'll pick different task
