### ISSUE TITLE
[FEAT] Create <Image /> utility component

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#21]
Description:
Create a utility component, <Image />, that simplifies the process of rendering images in a React application.

Acceptance Criteria:

- [ ] The <Image /> component should accept the image source URL as a prop and render the corresponding image.
- [ ] It should handle lazy loading of images to improve performance.
- [ ] Provide optional props to specify alt text, fallback images, and other image-related attributes.

**Comment by Giovym** [comment]
Hi David, can I take this issue?

**Comment by DavidHDev** [comment]
Sure thing, I'll assign it to you! Please read the CONTRIBUTING.MD file as well, thanks!
