### ISSUE TITLE
[FEAT] Create <Class /> utility component

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#22]
Description:
Implement a utility component, <Class />, that simplifies adding or removing CSS classes dynamically in a React application.

Acceptance Criteria:

- [ ] The <Class /> component should accept a className prop and apply the corresponding CSS class to the rendered element.
- [ ] It should provide additional props or functions to conditionally add or remove classes based on specific conditions.

**Comment by ansh-tripathi** [comment]
Hello David,
Can I work on this issue?
