### ISSUE TITLE
[FEAT] Convert library to TypeScript as a default

### ISSUE THREAD

**Issue by m10rten** [DavidHDev/react-haiku#28]
We can easily convert it to TS, should that be done?
With the tsup package we can then project it back to js and its variants.

**Comment by DavidHDev** [comment]
I really wouldn't want to complicate it with any packages, it should be 100% converted TS to keep it clean/depencency-free

**Comment by m10rten** [comment]
Ill take this, can't assign on mobile.

**Comment by m10rten** [comment]
Issued in #45

**Comment by DavidHDev** [comment]
Looks great, thanks!
