### ISSUE TITLE
Add TypeScript Support For Hooks & Utils

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#4]
At the moment react-haiku can not be used in `react-ts` projects since the `index.d.ts` file for the package has not been properly configured.

**Comment by Arthurmtro** [comment]
Could you make it compatible please, would be awesome !

**Comment by Yashkapure06** [comment]
Till when this issue is gonna be resolved?

**Comment by nicofrem** [comment]
Hi 😄
I added a PR that fixes it https://github.com/DavidHDev/react-haiku/pull/7
