### ISSUE TITLE
[FEAT] Add prettier dev formatting

### ISSUE THREAD

**Issue by m10rten** [DavidHDev/react-haiku#41]
Using a standard prettier config, the entire codebase will be in sync.

- creates a .prettierrc.json
- installs prettier as dev dependency
- adds a settings.json file in the .vscode folder to ensure everyone that uses vscode has the formatOnSave setting on true and the prettier module path to the node modules so the same prettier version is used.

**Comment by sahesh** [comment]
can i take this ? :)

**Comment by DavidHDev** [comment]
go for it @sahesh

**Comment by plbstl** [comment]
hey @sahesh, are you still working on this?
