### ISSUE TITLE
Add prettier to allow for a more consistent code style format

### ISSUE THREAD

**Issue by plbstl** [DavidHDev/react-haiku#49]
It's basically the title. I can quickly do this. And add a pre-commit hook for this also.

With the current codebase, this is the prettier config I suggest:

```json
{
    "printWidth": 120,
    "semi": false,
    "tabWidth": 4
}
```

**Comment by m10rten** [comment]
there is a ticket for this #41

**Comment by plbstl** [comment]
okay, thank you
