### ISSUE TITLE
[FEAT] Create Hook - useIntersectionObserver()

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#60]
**Description**
A hook that observes changes in the intersection of a target element with an ancestor element or viewport.

**Acceptance Criteria**

- [x] Element Visibility: Detects when the target element enters or exits the viewport.
- [x] Threshold/Margin Configuration: Allows configuration  thresholds/rootMargin.
- [x] Animate Once: Add the option to only animate the observed element only once on scroll.
- [x] Cleanup: Properly disconnects the observer when the component is unmounted.

**Comment by francoisdillinger** [comment]
Is this a repost or updated Intersection Observer hook?

**Comment by DavidHDev** [comment]
@francoisdillinger  just forgot to close the issue 👍🏻
