### ISSUE TITLE
[FEAT] Create Hook - useWindowSize()

### ISSUE THREAD

**Issue by DavidHDev** [DavidHDev/react-haiku#64]
**Description**
A hook that provides the current window dimensions.

**Acceptance Criteria**
- [ ] Dimensions: Returns the current width and height of the window.
- [ ] Cleanup: Removes resize event listeners when the component is unmounted

**Comment by francoisdillinger** [comment]
@DavidHDev, can I tackle this or do I need it assigned to me first? I noticed most features have requests so just wanted to make sure to not step on any toes. Thanks.

**Comment by DavidHDev** [comment]
Hey @francoisdillinger , contributing used to require assignment, but that got messy, so I think the best way moving forward is to skip that. 

Right now I propose we operate with this rule in mind: whoever opens the PR first with this issue mentioned, will be the one who gets to contribute with that Feature.

So feel free to take this for yourself and open a PR! Also, please have a quick read of `CONTRIBUTING.md` if you haven't already. Thank you!
